export const authErrors = {
	emailAlreadyTaken: {
		title: "Ops! Já temos um usuário com este e-mail",
		description: "Por favor, selecione um outro e-mail para prosseguir",
	},
	documentAlreadyTaken: {
		title: "Ops! Já temos um usuário com este CPF",
		description: "Revise as informações e tente novamente",
	},
	unauthorized: {
		title: "Credenciais inválidas",
		description: "Verifique as informações e tente novamente",
	},
	unknownError: {
		title: "Houston, temos um problema",
		description: "Tente novamente mais tarde",
	},
}
